#!/bin/sh

PROJECT_DIR=$(dirname $0)
PROJECT_DIR=$HOME/Projects/AlgoQuest

export AQUTIL_SOURCE_DIR="${PROJECT_DIR}/AQUtil"
export AQUTIL_LIBRARY_DIR="{PROJECT_DIR}/AQUtil/lib"

export AQQUERY_RESOLVER_SOURCE_DIR="${PROJECT_DIR}/AQQueryResolver"
export AQQUERY_RESOLVER_LIBRARY_DIR="${PROJECT_DIR}/AQQueryResolver/lib"
